BEGIN
	CW_AUCTION_TIMEOUT;
	CW_AUCTION_LOCK;
	IF :CWARCCPM.CM_BALANCE IS NOT NULL THEN
	--	FND_MESSAGE.DEBUG('INSIDE WHEN BUTTON PRESSED');
	show_window('CREDIT_OVERRIDE');
	go_block('CREDIT_OVERRIDE');
	EXECUTE_QUERY;
	ELSE
		NULL;
	END IF;
END;

/*begin
	IF :CWARCCPM.CM_BALANCE IS NULL THEN
		--	APP_ITEM_PROPERTY.SET_PROPERTY('CWARCCPM.VIEW_OVERRIDE',ENABLED,PROPERTY_FALSE); 
		NULL;
	ELSE
	show_window('CREDIT_OVERRIDE');
	go_block('CREDIT_OVERRIDE');
	--CW_CUST_OVERRIDE;
	EXECUTE_QUERY;
	END IF;
	/*IF :CWARCCPM.AUC_STATUS = 'Approval Failed' THEN
			EXECUTE_QUERY;
	END IF;	*/
	
/*	IF :CWARCCPM.AUC_STATUS IN ( 'Approval Failed','Approved & Receipt Created','Approved & Receipt Not Created') THEN
			EXECUTE_QUERY;
	END IF;*/
	
/*	IF :AUC_STATUS IN ('R','X') THEN
				EXECUTE_QUERY;
	END IF;	
end;*/

	