/*
****************************************************************
**  ATT CUSTOMIZATIONS
****************************************************************
**                                                      
**  FILE NAME: CUST_DEMANTRA_LOADER_ERR_MSG.sql
**
**  THIS SCRIPT CREATES THE ERROR MESSAGE FOR DEMANTRA LOADER PROGRAM
**
**  MODIFICATION HISTORY:
**  29/04/2015 KAUSHIKI CHOWDHURY  INITIAL CREATION
**                        
****************************************************************
*/
SET SERVEROUTPUT ON SIZE 100000

SET DEFINE OFF;
-------------------------------------------CUSTOMER FORECAST ERROR MESSAGES----------------------------------------------------
Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_ITEM_FORMAT_1', 'F05-20100: ITEM FORMAT IS INCORRECT FOR &ITEM CORRECT FORMAT IS ABC.XXXXXXX. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_ITEM_DATA_0', 'F05-20101: ITEM DATA IS INCORRECT. ', 
    SYSDATE,1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_PRIME_ITM_0', 'F05-20102: ITEM IS NOT A PRIME ITEM. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_REG_FORMAT_1', 'F05-20103: REGION FORMAT FOR &REGION IS INCORRECT. CORRECT FORMAT IS 2 CHARARCTER REGION CODE. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_DATE_FORMAT_1', 'F05-20104: DATE FORMAT IS INCORRECT FOR &DATE. CORRECT FORMAT IS MM/DD/YYYY. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_DATE_DATA_0', 'F05-20105: DATE FIELD HAS NULL VALUE IN IT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_FCST_DATE_RANGE_0', 'F05-20106: FORECAST DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_FCST_DATA_0', 'F05-20107: FORECAST DATA IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_NOTES_DATE_RANGE_0', 'F05-20108: NOTES DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );
---------------------------------------------------- PURCHASE FORECAST ERROR MESSAGES------------------------------------------------------------------
Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_OEM_DATA_0', 'F05-20109: OEM FIELD HAS NULL VALUE IN IT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );
    
Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_HIST_DATE_RANGE_0', 'F05-20110: HISTORY DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_HIST_DATA_0', 'F05-20111: HISTORY DATA IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_HIST_AVG_DATE_RANGE_0', 'F05-20113: HISTORY AVG DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_HIST_AVG_DATA_0', 'F05-20114: HISTORY AVG DATA IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_OHB_DATE_RANGE_0', 'F05-20115: ON HAND BALANCE DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_OHB_DATA_0', 'F05-20116: ON HAND BALANCE DATA IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_BCKORD_DATE_RANGE_0', 'F05-20117: BACK ORDER DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_BCKORD_DATA_0', 'F05-20118: BACK ORDER DATA IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_OPENPO_DATE_RANGE_0', 'F05-20119: OPEN PO DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_OPENPO_DATA_0', 'F05-20120: OPEN PO DATA IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_PASTDUE_DATE_RANGE_0', 'F05-20121: PAST DUE DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_PASTDUE_DATA_0', 'F05-20122: PAST DUE DATA IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );

Insert into FND_NEW_MESSAGES
   (APPLICATION_ID, LANGUAGE_CODE, MESSAGE_NUMBER, MESSAGE_NAME, MESSAGE_TEXT, CREATION_DATE, CREATED_BY, LAST_UPDATE_DATE, LAST_UPDATED_BY, TYPE)
Values
   (20045, 'US', CCW_ERR_MSG_SEQ.NEXTVAL, 'ERROR_COMMENTS_DATE_RANGE_0', 'F05-20123: COMMENTS DATE RANGE IS INCORRECT. ', 
    SYSDATE, 1, SYSDATE, 1, 'ERROR' 
    );
commit;
SHOW ERRORS;
exit;
/



